name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *" # Har kuni soat 00:00 da ishga tushadi
  workflow_dispatch: # Qo'lda ishga tushirish imkoniyati

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate Snake Game
        uses: Platane/snk@v2
        with:
          github_user_name: Metasensei # Profilingiz nomi
          outputs: dist/snake.svg

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: snake
          path: dist/snake.svg